name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 15]
    name: Java ${{ matrix.java }} sample

    steps:
    - name: Checkout calimero-core
      uses: actions/checkout@v2
      with:
        repository: calimero-project/calimero-core
        path: calimero-core
    - name: Checkout calimero-device
      uses: actions/checkout@v2
      with:
        repository: calimero-project/calimero-device
        path: calimero-device
    - name: Checkout calimero-rxtx
      uses: actions/checkout@v2
      with:
        repository: calimero-project/calimero-rxtx
        path: calimero-rxtx
    - name: Checkout calimero-server
      uses: actions/checkout@v2
      with:
        path: calimero-server
    - name: setup
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: |
        cd calimero-server
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd calimero-server
        ./gradlew build
